### PR TITLE
add elementary icons too

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by nedrichards** [comment]
When rebuilt I'll queue manual rebuilds for the apps that use this to make sure it's included.

**Comment by bilelmoussaoui** [comment]
The icons can't be installed on a baseApp as they don't follow the same RDNN style.

**Comment by bilelmoussaoui** [comment]
Is there anything that could solve this ?

**Comment by bilelmoussaoui** [comment]
Never mind what I said. We just need to trigger a new build for the apps. Totally forgot it was a baseApp and not a runtime

**Comment by nedrichards** [comment]
Hrm, that's proving difficult - I think they'll need manual patches anyway, so probably best to leave it until they get rebuilt 'naturally'

**Comment by bilelmoussaoui** [comment]
@nedrichards Can you trigger a build for playmymusic, please?

**Pull request merged**
